import { Inter, Roboto } from 'next/font/google'
import type { Metadata } from "next";
import "./globals.css";
import PersistentCTABanner from "@/components/CTABanner";
import Footer from "@/components/layouts/Footer";
import Navbar from "@/components/layouts/Navbar";


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <PersistentCTABanner />
      </body>
    </html>
  );
}
